# Generated by Django 3.2.8 on 2023-05-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0009_delete_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='pic',
            field=models.FileField(default=0, null=True, upload_to='fapp/static/pic'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fapp.product1')),
            ],
        ),
    ]
